version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
    post_build:
      commands:
        - echo Build completed on `date`
        - mvn package
    artifacts:
      files:
      - target/UserManagement-0.0.1-SNAPSHOT.jar